name: Test branches

on:
  push:
    branches: ['*']

  workflow_dispatch:

jobs:
  Pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test
      - name: E2E
        run: npm test
      - name: Build
        run: npm run build